name: ml-hyperopt
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '5 5 * * *'

jobs:
  build:
    name: ml-hyperopt ci
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java_version: ['11.0.4']

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
          architecture: x64

      - name: Tests
        run: |
          curl -fsSL get.nextflow.io | bash
          ./nextflow run . -profile wave
        env:
          NXF_ANSI_LOG: false
